version: "3"
services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    networks:
      - bp
  hi-service:
    build:
      context: ./service-hi
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
    ports:
      - 8762:8762
    links:
      - eureka-server
    networks:
      - bp
volumes:
  cloud:
    external: true
networks:
  bp:
    external: true