server:
    port: 8761


eureka:
    instance:
        hostname: localhost
        prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

spring:
    application:
        name: eurka-server
    security:
        basic:
            enabled: true
        user:
            name: user
            password: 12345
