server:
  port: 8762

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      #defaultZone: http://eureka-server:8761/eureka/
      defaultZone: http://user:12345@localhost:8761/eureka/