server:
  port: 8762

spring:
  application:
    name: service-hi

eureka:
  instance:
    instance-id: ${spring.cloud.client.ipaddress}:${eureka.instance.appname}:${server.port}
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
  client:
    serviceUrl:
      #defaultZone: http://eureka-server:8761/eureka/
      defaultZone: http://user:12345@localhost:8761/eureka/