server:
  port: 8762

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      #defaultZone: http://eureka-server:8761/eureka/
      defaultZone: http://127.0.0.1:8761/eureka/