
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:12345@localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon
logging:
  level:
    org.daming.service.ribbon.HelloFeignClient: INFO
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
management:
  endpoints:
    web:
      exposure:
        include: "*"
        #include: health,info,hystrix.stream,actuator #根据需求增删路径